#!/usr/bin/env python3

from cenai_core import Logger
from cenai_core.grid import GridCLI, GridRunner


class ResearchReportSummarization(Logger):
    logger_name = "cenai.system"

    def __init__(self):
        super().__init__()

        self._cli = GridCLI(
            title="Research report summarizer",
            runner=GridRunner,
            search_name="profile",
            search_dir="%python/research_report_summarizer/profile",
            search_pattern="*.yaml",
            search_type="file",
        )

    def __call__(self) -> None:
        self._cli.invoke()


if __name__ == "__main__":
    try:
        research_report_summarize = ResearchReportSummarization()
        research_report_summarize()

    except Exception as error:
        ResearchReportSummarization.ERROR(error)
        exit(-1)
